"""Validation helper for caller-supplied workbook paths (H-06).

Confines a ``workbook_path`` value to one of the trusted shapes the
platform expects:

* an HTTPS blob URI on an allow-listed host (downloaded by the storage
  backend into a controlled cache), or
* a path that resolves under one of the allowed local base directories
  (``UPLOAD_DIR``, ``APP_OUTPUT_DIR``, ``ORCHESTRATOR_TMP_DIR``, or the
  system temp directory).

Any value that includes ``..`` segments, a NUL byte, an unknown URL
scheme, or that resolves outside those bases is rejected with a
``ValueError`` so the caller fails fast instead of opening an arbitrary
file on the container's filesystem.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from urllib.parse import urlparse


DEFAULT_EXCEL_EXTENSIONS: tuple[str, ...] = (
    ".xlsx", ".xlsm", ".xltx", ".xltm", ".xlsb", ".xls", ".csv",
)

_ALLOWED_BLOB_HOST_SUFFIXES: tuple[str, ...] = (
    ".blob.core.windows.net",
    ".dfs.core.windows.net",
)
_ALLOWED_BLOB_HOSTS_EXACT: tuple[str, ...] = (
    "localhost",
    "127.0.0.1",
    "azurite",
    "host.docker.internal",
    "devstoreaccount1.blob.core.windows.net",
)


def _platform_host() -> str | None:
    """Extract the hostname from SERVICE_BASE_URL."""
    base = os.getenv("SERVICE_BASE_URL", "").strip()
    if base:
        return (urlparse(base).hostname or "").lower() or None
    return None


def _allowed_base_dirs(additional: list[Path] | None = None) -> list[Path]:
    bases: list[Path] = []
    for env in ("UPLOAD_DIR", "APP_OUTPUT_DIR", "ORCHESTRATOR_TMP_DIR"):
        v = os.getenv(env)
        if v:
            try:
                bases.append(Path(v).resolve())
            except OSError:
                continue
    try:
        bases.append(Path(tempfile.gettempdir()).resolve())
    except OSError:
        pass
    if additional:
        for p in additional:
            try:
                bases.append(Path(p).resolve())
            except OSError:
                continue
    # de-duplicate while preserving order
    seen: set[str] = set()
    unique: list[Path] = []
    for b in bases:
        s = str(b)
        if s not in seen:
            seen.add(s)
            unique.append(b)
    return unique


def _is_allowed_blob_uri(value: str) -> bool:
    """Return True if value is a blob URI on an allow-listed host."""
    parsed = urlparse(value)
    scheme = parsed.scheme.lower()

    # Platform-internal locator schemes used by AzureBlobBackend
    if scheme in {"azure", "blob"}:
        rest = value.split("://", 1)[1] if "://" in value else ""
        container, _, key = rest.partition("/")
        return bool(container) and bool(key)

    if scheme not in {"http", "https"}:
        return False
    host = (parsed.hostname or "").lower()
    if not host:
        return False
    if host in _ALLOWED_BLOB_HOSTS_EXACT:
        return True
    platform = _platform_host()
    if platform and host == platform:
        return True
    return any(host.endswith(suffix) for suffix in _ALLOWED_BLOB_HOST_SUFFIXES)


import re

_INTERNAL_FILE_MANAGER_PATTERN = re.compile(
    r"^(?:/file-manager)?/api/v\d+/(?:internal/)?files/[0-9a-f\-]{32,36}(?:/download)?$"
)


def _is_internal_file_manager_url(url_path: str) -> bool:
    """Return True if url_path matches the platform file-manager pattern."""
    return bool(_INTERNAL_FILE_MANAGER_PATTERN.match(url_path))


def validate_workbook_path(
    raw: str,
    *,
    allowed_extensions: tuple[str, ...] = DEFAULT_EXCEL_EXTENSIONS,
    additional_allowed_bases: list[Path] | None = None,
) -> str:
    """Return ``raw`` unchanged if safe; otherwise raise ``ValueError``.

    Accepts blob URIs on allow-listed hosts, or local paths confined to
    an allowed base directory. Rejects ``..`` traversal, NUL bytes,
    unknown URL schemes, and absolute paths that escape the allowed
    bases.
    """
    candidate = (raw or "").strip()
    if not candidate:
        raise ValueError("workbook_path is empty")
    if "\x00" in candidate:
        raise ValueError("workbook_path contains NUL byte")

    if "://" in candidate:
        parsed_url = urlparse(candidate)
        url_path = (parsed_url.path or "").lower()
        # Platform-internal file-manager URLs are generated by the platform
        # itself and are trusted regardless of internal hostname.
        # Check these before the external host allowlist.
        if _is_internal_file_manager_url(url_path) and parsed_url.scheme.lower() in {"http", "https"}:
            return candidate
        if not _is_allowed_blob_uri(candidate):
            raise ValueError(
                f"workbook_path scheme/host not allowed: {candidate!r}"
            )
        # Internal file-manager URLs serve files by UUID without extension.
        if _is_internal_file_manager_url(url_path):
            return candidate
        if not url_path.endswith(allowed_extensions):
            raise ValueError(
                f"workbook_path must reference an Excel file, got: {candidate!r}"
            )
        return candidate

    if not candidate.lower().endswith(allowed_extensions):
        raise ValueError(
            f"workbook_path must reference an Excel file, got: {candidate!r}"
        )

    p = Path(candidate)
    if any(part == ".." for part in p.parts):
        raise ValueError(f"workbook_path must not contain '..': {candidate!r}")

    bases = _allowed_base_dirs(additional=additional_allowed_bases)

    if p.is_absolute():
        try:
            resolved = p.resolve()
        except OSError as exc:
            raise ValueError(
                f"workbook_path cannot be resolved: {candidate!r}"
            ) from exc
        for base in bases:
            try:
                resolved.relative_to(base)
                return str(resolved)
            except ValueError:
                continue
        raise ValueError(
            f"workbook_path resolves outside allowed base directories: {candidate!r}"
        )

    for base in bases:
        try:
            cand = (base / p).resolve()
            cand.relative_to(base)
            return candidate
        except (OSError, ValueError):
            continue
    raise ValueError(
        f"workbook_path does not resolve under any allowed base directory: {candidate!r}"
    )
